export const initialState = {
  rating: [],
  link: '',
  poster: false,
  viewAddProduct: false,
  basket: [],
  openCatalog: false,
  openFormModal: false,
  categoryProduct: { subCategory: {}, category: {} },
  error: null,
  products: {
    location: '',
    product: [],
    totalPage: 0,
    filters: {},
    search: [],
    prevSearch: [],
    isLoading: true,
    isLoadingSearch: false,
    loader: false,
  },
  productPage: {
    product: {},
    isLoading: true,
    createCommentLoading: false,
    commentsExpanded: new Set(),
  },
  user: {
    lastName: '',
    firstName: '',
    surname: '',
    birthName: '',
    gender: '',
    profilePictureSrc: '',
    email: '',
    phoneNumber: '',
  },
  users: {
    token: null,
    isLoading: true,
    isRending: true,
    isActivated: false,
    myUser: null,
    _id: null,
    user: {
      firstName: '',
      lastName: '',
      numberPhone: '',
      email: '',
      password: '',
    },
  },
  orderData: {
    firstName: '',
    lastName: '',
    tel: '',
    email: '',
    town: '',
    wayDelivery: '',
    postOffice: '',
    street: '',
    building: '',
    floor: '',
    apartment: '',
    pay: '',
    products: [],
  },
};
